apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: argo-rollouts
  labels:
    name : "Dashboard"
    icon : "fa-table-columns"
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
  - web:
      url: https://github.com/OpsMx/rollout-extension/releases/download/v0.2.1.3/extension.tar
